changeLogFile: db/changelog/changelog.xml
url: mongodb://localhost:27017/rgr_db
driver: liquibase.ext.mongodb.database.MongoClientDriver
classpath: lib/liquibase-mongodb-5.0.2.jar;lib/mongodb-driver-sync-4.10.2.jar;lib/mongodb-driver-core-4.10.2.jar;lib/bson-4.10.2.jar